// <auto-generated />
namespace GL.DBOptions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class update_imgage_appid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_imgage_appid));
        
        string IMigrationMetadata.Id
        {
            get { return "201606020115218_update_imgage_appid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
