// <auto-generated />
namespace GL.DBOptions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updata_app_author : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updata_app_author));
        
        string IMigrationMetadata.Id
        {
            get { return "201606260102221_updata_app_author"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
